<script setup lang="ts">
import { computed, nextTick, ref } from 'vue'
import AnimatedNumber from './AnimatedNumber.vue'
const props = withDefaults(defineProps<{value:number;label?:string;caption:string;source:string;updatedAt:string;resetAt?:string;size?:number;warning?:boolean;tooltipPlacement?:'below'|'left'}>(),{label:'',resetAt:'',size:54,warning:false,tooltipPlacement:'below'})
const root=ref<HTMLElement|null>(null),open=ref(false),tipStyle=ref<Record<string,string>>({})
const safeValue=computed(()=>Math.max(0,Math.min(100,Number.isFinite(props.value)?props.value:0)))
const stroke=computed(()=>Math.max(4,Math.round(props.size*.105)))
async function show(){open.value=true;await nextTick();const box=root.value?.getBoundingClientRect();if(!box)return;const width=220,left=Math.max(12,Math.min(innerWidth-width-12,props.tooltipPlacement==='left'?box.left-width-10:box.right-width));let top=props.tooltipPlacement==='left'?box.top+box.height/2-72:box.bottom+8;if(top+148>innerHeight)top=Math.max(12,box.top-156);tipStyle.value={left:`${left}px`,top:`${top}px`}}
function hide(){open.value=false}
function toggle(){open.value?hide():show()}
</script>
<template><span ref="root" class="smooth-ring" :class="{warning,open}" :style="{'--ring-size':`${size}px`,'--ring-stroke':`${stroke}px`}" tabindex="0" role="img" :aria-label="`${caption} ${safeValue}%`" @mouseenter="show" @mouseleave="hide" @focusin="show" @focusout="hide" @click.stop="toggle"><svg viewBox="0 0 48 48" aria-hidden="true"><circle class="smooth-ring__track" cx="24" cy="24" r="19" pathLength="100"/><circle class="smooth-ring__value" cx="24" cy="24" r="19" pathLength="100" :style="{strokeDashoffset:`${100-safeValue}`}"/><circle class="smooth-ring__highlight" cx="24" cy="24" r="15.5"/></svg><b class="smooth-ring__label"><AnimatedNumber v-if="!label" :value="safeValue" format="percent"/><template v-else>{{label}}</template></b><Teleport to="body"><Transition name="ring-tip"><span v-if="open" class="smooth-ring__tooltip" :style="tipStyle" role="tooltip" @mouseenter="show" @mouseleave="hide"><strong>{{caption}}</strong><span><b>当前值</b><i><AnimatedNumber :value="safeValue" format="percent"/></i></span><span><b>数据来源</b><i>{{source}}</i></span><span><b>更新时间</b><i>{{updatedAt}}</i></span><span v-if="resetAt"><b>重置时间</b><i>{{resetAt}}</i></span></span></Transition></Teleport></span></template>
<style scoped>.smooth-ring{position:relative;display:grid;width:var(--ring-size);height:var(--ring-size);flex:0 0 auto;place-items:center;border-radius:50%;outline:none;isolation:isolate}.smooth-ring svg{position:absolute;inset:0;width:100%;height:100%;overflow:visible;filter:drop-shadow(0 5px 10px color-mix(in srgb,var(--tm-accent,#007aff) 12%,transparent));transform:rotate(-90deg)}.smooth-ring circle{fill:none;stroke-width:var(--ring-stroke)}.smooth-ring__track{stroke:color-mix(in srgb,var(--tm-ink,#1d1d1f) 9%,transparent)}.smooth-ring__value{stroke:var(--tm-accent,var(--chart-1,#1d1d1f));stroke-dasharray:100;stroke-linecap:round;transition:stroke-dashoffset var(--tm-motion-data,.3s) var(--tm-ease-out,cubic-bezier(.22,1,.36,1)),stroke var(--tm-motion-normal,.22s) ease}.smooth-ring__highlight{stroke:color-mix(in srgb,var(--tm-bg,#fff) 52%,transparent);stroke-width:1;opacity:.65}.smooth-ring.warning .smooth-ring__value{stroke:#ff3b30}.smooth-ring__label{position:relative;z-index:1;max-width:70%;overflow:hidden;color:var(--tm-ink,#1d1d1f);font-size:10px;font-variant-numeric:tabular-nums;line-height:1;text-overflow:ellipsis;white-space:nowrap}.smooth-ring:where(:hover,:focus-visible,.open) .smooth-ring__value{filter:drop-shadow(0 0 4px color-mix(in srgb,currentColor 28%,transparent))}.smooth-ring:focus-visible{box-shadow:0 0 0 3px color-mix(in srgb,var(--tm-accent,#007aff) 20%,transparent)}.smooth-ring__tooltip{position:fixed;z-index:2147483000;display:grid;width:min(220px,calc(100vw - 24px));box-sizing:border-box;gap:7px;padding:11px 12px;border:1px solid color-mix(in srgb,var(--tm-ink,#1d1d1f) 13%,transparent);border-radius:13px;background:var(--tm-bg,#fff);box-shadow:0 16px 38px color-mix(in srgb,var(--tm-ink,#1d1d1f) 18%,transparent);color:var(--tm-ink,#1d1d1f);font:10px/1.45 "PingFang SC","Microsoft YaHei",sans-serif;text-align:left;opacity:1}.smooth-ring__tooltip>strong{font-size:11px}.smooth-ring__tooltip>span{display:grid;grid-template-columns:auto minmax(0,1fr);gap:9px}.smooth-ring__tooltip b{color:var(--tm-muted,#6e6e73);font-size:9px;font-weight:500}.smooth-ring__tooltip i{overflow:hidden;font-size:9px;font-style:normal;text-align:right;text-overflow:ellipsis;white-space:nowrap}.ring-tip-enter-active,.ring-tip-leave-active{transition:opacity var(--tm-motion-fast,.16s) ease,transform var(--tm-motion-normal,.22s) var(--tm-ease-out,cubic-bezier(.22,1,.36,1))}.ring-tip-enter-from,.ring-tip-leave-to{opacity:0;transform:translateY(-1px) scale(.985)}@media(prefers-reduced-motion:reduce){.smooth-ring__value,.ring-tip-enter-active,.ring-tip-leave-active{transition:none}}:global(.motion-off) .smooth-ring__value,:global(.motion-off) .ring-tip-enter-active,:global(.motion-off) .ring-tip-leave-active{transition:none}</style>
