import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import './styles.css'
import './floating.css'
import './apple-fonts.css'
import './apple-design-system.css'
import './liquid-glass.css'
import './spring-motion.css'
import './white-mode.css'
import './window-chrome.css'
import './liquid-clear-unified.css'
import './liquid-transparency.css'
createApp(App).use(createPinia()).mount('#app')
